// Generates www/index.html from dg-node's search/index.html.
//
// This script is the reason the app's main page can stop being a hand-made copy. It used to be
// copied by hand — build-assets.js's header referenced a "build-page.js" that was never written —
// and by the time the app moved out of dg-node that copy had drifted 147 lines behind the site,
// of which only 4 were intentional. Every one of the other ~143 was a site fix the app shipped
// without.
//
// The real delta between the site's page and the app's page is exactly two edits:
//
//   1. three <script> tags at the very top of <head> — app.js must install its fetch shim before
//      any other script on the page can issue a request, and native-bridge/offline-status hook
//      external links and download progress;
//   2. the service-worker registration block is dropped — there is no dg-light.js here to serve
//      /sw.js, and a SW would only compete with app.js's own fetch interception.
//
// Both are applied here, declaratively, so the page can never drift again.
//
// Anchors: if dg-node's search/index.html carries a `<!-- dg:app-scripts -->` marker we insert
// there; otherwise we insert right after <head>. The marker is the preferred form (it makes the
// insertion point explicit on the site's side) but is deliberately NOT required, so this repo
// builds against an unmodified dg-node checkout.
//
// Usage: node build-page.js

const fs = require('fs');
const path = require('path');
const { WWW, requireNodeRoot, f } = require('./paths');

const APP_SCRIPTS = `<!-- Offline data-shim: installs window.fetch interception BEFORE any other script/asset on this
     page can issue a real network request. Everything below is the REAL production page
     (dg-node's search/index.html), generated by build-page.js — reuse the real frontend, only
     swap its data layer, never rebuild the UI. -->
<script src="app.js"></script>
<!-- Routes memo/login/mirror-link's external opens through the device's real browser instead of
     this app's own WebView — see native-bridge.js for why plain navigation doesn't work here. -->
<script src="/native-bridge.js"></script>
<script src="/offline-status.js"></script>`;

const APP_SCRIPTS_MARKER = '<!-- dg:app-scripts -->';

// The whole <script> element that registers /sw.js, comments included. Matched on its distinctive
// call rather than on surrounding markup so re-indentation on the site's side doesn't break it.
const SW_BLOCK = /\n*<script>(?:(?!<\/script>)[\s\S])*?navigator\.serviceWorker\.register\((?:(?!<\/script>)[\s\S])*?<\/script>/;

const SW_REPLACEMENT = `
<!-- dg-node's service-worker registration is deliberately dropped here (build-page.js): there is
     no dg-light.js serving /sw.js in this app, and a SW would only compete with app.js's own
     fetch shim for the same requests. -->`;

function injectAppScripts(html) {
    if (html.includes(APP_SCRIPTS_MARKER)) {
        return html.replace(APP_SCRIPTS_MARKER, APP_SCRIPTS);
    }
    const head = html.indexOf('<head>');
    if (head === -1) throw new Error('search/index.html: no <head> and no dg:app-scripts marker');
    return html.slice(0, head + '<head>'.length) + '\n' + APP_SCRIPTS + html.slice(head + '<head>'.length);
}

function dropServiceWorker(html) {
    if (!SW_BLOCK.test(html)) {
        throw new Error(
            'search/index.html: service-worker registration block not found.\n' +
            'Either it was removed upstream (drop this step) or its shape changed (update SW_BLOCK).'
        );
    }
    return html.replace(SW_BLOCK, SW_REPLACEMENT);
}

// Cheap guards against a silently wrong page: every intended edit must be observable in the
// output. A page that builds but ships a live SW, or without the fetch shim, is worse than a
// build failure — it fails on the device, offline, where nobody is watching a console.
function verify(html) {
    const problems = [];
    for (const tag of ['app.js', '/native-bridge.js', '/offline-status.js']) {
        if (!html.includes(`src="${tag}"`)) problems.push(`missing <script src="${tag}">`);
    }
    if (html.includes('serviceWorker.register')) problems.push('service worker registration still present');
    if (html.indexOf('src="app.js"') > html.indexOf('<script src="/assets/')) {
        problems.push('app.js is not the first script — the fetch shim would install too late');
    }
    if (problems.length) throw new Error(`build-page.js produced a bad page:\n  - ${problems.join('\n  - ')}`);
}

function main() {
    requireNodeRoot();
    const src = f('search/index.html');
    let html = fs.readFileSync(src, 'utf8');
    const before = html.length;

    html = injectAppScripts(html);
    html = dropServiceWorker(html);
    verify(html);

    fs.mkdirSync(WWW, { recursive: true });
    const dest = path.join(WWW, 'index.html');
    fs.writeFileSync(dest, html, 'utf8');
    console.log(`Page: ${path.relative(process.cwd(), dest)} <- ${src} (${before} -> ${html.length} bytes)`);
}

main();
