// Offline data shim for the app. This file owns no UI: www/index.html is dg-node's own
// search/index.html, generated by build-page.js, and its inline SPA engine plus the real
// search-render.js / megareader.js / common.js drive everything the reader sees.
//
// Its only job is to intercept the handful of fetch() calls that need data and answer them
// locally. What answers them is NOT a reimplementation of the site's API: it is dg-node's own
// core/search-core.js, bundled by build-core-bundle.js and running in db-worker.js over a slice
// of the same dg.db the server queries. The app used to carry its own SQL, its own translator
// selection and its own result assembly, and they drifted — different counts, no match inside a
// compound, one translator per language, no punctuation stripping. Now there is one
// implementation, and test/core-parity.mjs diffs its answers against the site's.
//
// The database lives in the worker because OPFS hands out synchronous access handles only there,
// and synchronous access is what keeps a large database on disk instead of in memory.
//
// TOC (/api/toc, /api/toc/book/:code) stays a build-time snapshot of the live server's JSON (see
// build-toc-snapshot.js): its branch-title resolution changes with the corpus, not per request.

// App Shortcuts (long-press launcher icon, Android/MainActivity.java + res/xml/shortcuts.xml)
// can't loadUrl() straight to a deep path — the static asset server behind this origin has no
// file at e.g. "/toc/pli-tv-bu-pm" (only index.html at root), same reason a raw reload of a
// pushState'd URL 404s. MainActivity instead loads "/?_nativeRoute=<path>" on the root, and this
// runs FIRST — before the page's own bootstrap script (search/index.html's inline $(document).
// ready handler) ever reads window.location — rewriting the visible URL to the real target via
// the same history.replaceState() trick the SPA already uses for its own pushState navigation.
// A plain browser load (no native shortcut involved) never has this param, so this is a no-op.
// "favorites" App Shortcut (res/xml/shortcuts.xml) opens Favorites/History via a plain
// "?action=tab-fav" on the root URL — MainActivity generates it directly, no rewrite needed here.
// settings-bundle.js already listens for exactly this on DOMContentLoaded (the same hook the
// site's own "Быстрое окно" doc page uses), so it needs no shim of its own. A custom
// `_openQuickModal` param used to be rewritten here and opened via a `window.addEventListener(
// 'load', ...)` poll, but `load` waits on every subresource and isn't guaranteed to still be
// pending when the listener attaches — it reportedly just opened the home screen on real devices.
// DOMContentLoaded, which settings-bundle.js's own hook uses, has neither problem.
(function rewriteNativeShortcutRoute() {
    const params = new URLSearchParams(location.search);
    const route = params.get('_nativeRoute');
    if (route) history.replaceState(null, '', route);
})();

// Where the offline database is published: siteroot/mobile-data in dg-node, served from the live
// host. One file: dg-mobile.db, a language slice of the server's own dg.db, cut by
// build-app-db.js — named apart from it so the two never get confused on the same machine.
//
// Overridable so the app can be pointed at a local copy: the end-to-end test serves the database
// from the same origin as the page, and a staging build may want a different host. Set
// window.DG_DIST_BASE before this script runs — it is the first script on the page, so that means
// an init script or an injected tag above it.
const DIST_BASE = (typeof window !== 'undefined' && window.DG_DIST_BASE) || 'https://dhamma.gift/mobile-data';

let worker = null;
let ready = null;
let nextCallId = 1;
const pending = new Map();

function startWorker() {
    // A module worker: @sqlite.org/sqlite-wasm ships ESM only, and the core bundle is emitted as a
    // module for the same reason.
    const w = new Worker('/db-worker.js', { type: 'module' });
    w.onmessage = (event) => {
        const msg = event.data || {};
        // Unsolicited progress, so the UI can show something during the first download.
        if (msg.type === 'progress') {
            if (msg.retrying) console.log('[dg-download] stalled, retrying (attempt ' + msg.retrying + ')');
            window.dispatchEvent(new CustomEvent('dg:dl-progress', {
                detail: {
                    name: 'dg-mobile.db', step: 1, totalSteps: 1,
                    loaded: msg.loaded, total: msg.total, phase: msg.phase || 'download', done: !!msg.done,
                    reason: msg.retrying ? 'stalled, retrying (attempt ' + msg.retrying + ')' : null,
                },
            }));
            return;
        }
        if (msg.type === 'downloading') return;
        const entry = pending.get(msg.id);
        if (!entry) return;
        pending.delete(msg.id);
        msg.ok ? entry.resolve(msg.result) : entry.reject(new Error(msg.error));
    };
    w.onerror = (e) => {
        // A worker that fails to start (a bad import, a missing wasm) otherwise leaves every
        // caller hanging forever, which on a device looks like a frozen app rather than an error.
        const err = new Error('data worker failed: ' + (e.message || 'unknown'));
        for (const { reject } of pending.values()) reject(err);
        pending.clear();
    };
    return w;
}

function call(op, args) {
    return new Promise((resolve, reject) => {
        const id = nextCallId++;
        pending.set(id, { resolve, reject });
        worker.postMessage({ id, op, args });
    });
}

// Owner: "предупредить что даты много, и если мобильные данные — получить согласие" — Wi-Fi
// proceeds immediately (just the progress banner); anything else (cellular/unknown/no plugin
// info) asks first through a UI-owned dialog, wired by a plain event so this file needs no DOM
// code (offline-status.js listens for 'dg:need-consent' and calls the carried resolve).
async function hasNetworkConsent(info) {
    const Network = window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins.Network;
    if (!Network) return true;
    let status;
    try { status = await Network.getStatus(); } catch (e) { return true; }
    if (status.connectionType === 'wifi') return true;
    return new Promise(resolve => {
        // bytes comes from the published manifest, so the question names the size of the file that
        // is actually about to be transferred rather than a figure baked into the app.
        window.dispatchEvent(new CustomEvent('dg:need-consent', {
            detail: { resolve, bytes: info && info.bytes, langs: info && info.langs },
        }));
    });
}

async function loadData() {
    worker = worker || startWorker();

    // Consent is asked only when there is something to download. A returning reader whose copy is
    // already in OPFS must stay fully offline-capable and never wait on a network status call
    // that could itself hang — so the worker is asked whether the file is there first, and only a
    // missing one leads to a question. The dialog lives on this side because a worker has no DOM.
    const status = await call('status', { distBase: DIST_BASE });
    if (status.present) return call('open', { distBase: DIST_BASE });
    if (!(await hasNetworkConsent(status))) throw new Error('offline-data-download-declined');
    // Used to hand this off to Android's DownloadManager (so it would survive the app being
    // backgrounded) through a DgDownloader plugin. Dropped: several devices never actually ran
    // the queued request at all — DownloadManager sat at STATUS_PENDING or STATUS_RUNNING forever,
    // gave no error, and asked for POST_NOTIFICATIONS before saying so. The worker fetching the
    // file itself, the same as it does in a browser, is slower to survive backgrounding but is the
    // one path that has actually finished on a device.
    return call('open', { distBase: DIST_BASE });
}

function jsonResponse(obj, status = 200) {
    return new Response(JSON.stringify(obj), { status, headers: { 'Content-Type': 'application/json' } });
}

// A worker result may carry the status the route would have set: an unknown sutta is a 404, and
// answering 200 with an error body would be a different contract from the site's.
function respond(result) {
    if (result && result.__status) {
        const { __status, ...body } = result;
        return jsonResponse(body, __status);
    }
    return jsonResponse(result);
}

function withLoadingEvent(fn) {
    window.dispatchEvent(new CustomEvent('dg:api-loading', { detail: { active: true } }));
    return fn().finally(() => {
        window.dispatchEvent(new CustomEvent('dg:api-loading', { detail: { active: false } }));
    });
}

// Languages this app's own offline database slice was cut with (see build-app-db.js's
// --langs=ru,en in the workflow). Anything else the language picker offers exists on the corpus
// but isn't in THIS device's copy — a "частный случай" (edge case), fine to just require internet
// for rather than growing the bundled database, same call as needsOnline's script check below.
const OFFLINE_LANGS = ['ru', 'en'];

// Script conversion (?script=, "Система письма" in /settings/) runs through Aksharamukha on the
// server (Python/Pyodide) — dg-fastify.js's convertPaliScript()/convertScriptInSearchResult(),
// not core/search-core.js, so this app's local worker (which calls the core directly) has no
// equivalent and never will unless that ~30MB engine gets ported here too. Same call as
// OFFLINE_LANGS: a rarely-used option, online-only is an acceptable answer for it. 'isopali' is
// the default the client already omits (see search/index.html's own `scriptSetting !== 'isopali'`
// check before it even adds ?script= to a request) — treated the same as "absent" here.
function needsOnline(qs) {
    const script = qs.get('script');
    if (script && script.toLowerCase() !== 'isopali') return true;
    const langs = (qs.get('langs') || '').split(',').map((s) => s.trim()).filter(Boolean);
    return langs.some((l) => !OFFLINE_LANGS.includes(l));
}

// Installed synchronously, at the very top of <head> (see build-page.js) — before any other
// script or asset on the page can issue a real fetch(). Requests this doesn't recognise pass
// straight through to the real fetch: static JSON/HTML/CSS/JS all resolve as plain local files.
function installFetchShim() {
    const realFetch = window.fetch.bind(window);
    // https://localhost (this app's own origin) has no server behind it for anything dynamic —
    // used for requests that must go to the actual internet: a non-default script or a language
    // outside this device's bundled slice (needsOnline above), and /api/transliterate, which has
    // no local equivalent at all (paliLookup.js's ensureIastWord() already fetches it against
    // `location.origin`, i.e. this app's own dead-end origin, unaware it's running inside the
    // app rather than on the live site). Forwarding to the real host makes these behave exactly
    // like the site when a connection exists, and fail visibly and fast, like any other
    // unreachable fetch, when it doesn't — no bespoke "you're offline" handling needed here,
    // callers of both already tolerate a failed fetch (ensureIastWord catches it and falls back
    // to the untransliterated word; search/reader show the same error state the site itself
    // would on a dropped connection).
    window.fetch = async (input, init) => {
        const url = typeof input === 'string' ? input : input.url;
        let parsed;
        try { parsed = new URL(url, location.href); } catch (e) { return realFetch(input, init); }
        const p = parsed.pathname;
        const qs = parsed.searchParams;
        const toOnline = () => realFetch('https://dhamma.gift' + p + parsed.search, init).catch((e) => {
            // Without this, a failed forward here surfaces as the site's generic "Search error —
            // check your query (invalid regular expression?)" message (index.html's own catch
            // block) — flatly wrong for "you picked a script/language this device doesn't have
            // offline and there's no connection", and gives the reader nothing to act on.
            // showBubbleNotification is settings-bundle.js's own existing toast (Settings-applied,
            // language-switched, etc.) — reused rather than inventing a second one.
            if (typeof window.showBubbleNotification === 'function') {
                const ru = (localStorage.getItem('dhammaLanguage') || localStorage.getItem('siteLanguage') || 'en') === 'ru';
                window.showBubbleNotification(ru
                    ? 'Нужен интернет: эта система письма или язык не входят в офлайн-библиотеку'
                    : 'Needs internet: this script or language isn’t in the offline library', 5000);
            }
            throw e;
        });

        if (p === '/api/transliterate') return toOnline();

        if (p.startsWith('/api/text/')) {
            if (needsOnline(qs)) return toOnline();
            return withLoadingEvent(async () => {
                await ready;
                return respond(await call('text', {
                    suttaId: decodeURIComponent(p.slice('/api/text/'.length)).toLowerCase(),
                    mode: qs.get('mode'),
                    langs: qs.get('langs'),
                    lang: qs.get('lang'),
                    translators: qs.get('translators'),
                    multiFor: qs.get('multiFor'),
                }));
            });
        }
        if (p.startsWith('/api/nav/')) {
            await ready;
            return respond(await call('nav', {
                suttaId: decodeURIComponent(p.slice('/api/nav/'.length)).toLowerCase(),
                scope: qs.get('scope'),
            }));
        }
        // TOC — baked at build time (build-toc-snapshot.js curls the live server once) rather than
        // reimplemented: dg-fastify.js's branch-title resolution (colophon lookups, curated SN
        // overrides) only changes when the corpus or toc-books.json does, which is the same
        // cadence as the database itself. No `await ready` — these are static files.
        if (p === '/api/toc') return realFetch('/api-snapshots/toc.json', init);
        if (p.startsWith('/api/toc/book/')) {
            return realFetch(`/api-snapshots/toc-book-${decodeURIComponent(p.slice('/api/toc/book/'.length))}.json`, init);
        }
        // The file is already bundled at reader/{bu,bi}-pm-fragment.html — only the URL differs.
        if (p.startsWith('/api/patimokkha-fragment/')) {
            const side = p.slice('/api/patimokkha-fragment/'.length);
            if (side !== 'bu' && side !== 'bi') return jsonResponse({ error: 'Not found' }, 404);
            return realFetch(`/reader/${side}-pm-fragment.html`, init);
        }
        if (p === '/search/enrich') {
            if (needsOnline(qs)) return toOnline();
            await ready;
            return respond(await call('enrich', {
                q: qs.get('q') || '', ids: qs.get('ids') || '', langs: qs.get('langs') || 'ru,en',
                scope: qs.get('scope') || 'default', exact: qs.get('exact') === 'true',
                lb: parseInt(qs.get('lb')) || 0, la: parseInt(qs.get('la')) || 0,
            }));
        }
        if (p === '/search' || (p.startsWith('/search/') && p !== '/search/enrich')) {
            if (needsOnline(qs)) return toOnline();
            return withLoadingEvent(async () => {
                await ready;
                return respond(await call('search', {
                    q: p === '/search' ? (qs.get('q') || '') : decodeURIComponent(p.slice('/search/'.length)),
                    scope: qs.get('scope') || 'default',
                    langs: qs.get('langs') || 'ru,en',
                    exact: qs.get('exact') === 'true',
                    lb: parseInt(qs.get('lb')) || 0,
                    la: parseInt(qs.get('la')) || 0,
                    fast: qs.get('fast') === '1',
                }));
            });
        }
        return realFetch(input, init);
    };
}

installFetchShim();
ready = loadData();
window.dgOfflineReady = ready;
ready.catch(() => {}); // declining rejects `ready`; real awaiters see it through their own await

// Settings' "Download now"/"Re-download" button and offline-status.js's retry share this path.
window.dgRetryOfflineDownload = function () {
    ready = loadData();
    window.dgOfflineReady = ready;
    ready.catch(() => {});
    return ready;
};

// A copy in OPFS is used forever unless something asks whether it is still the current one — which
// is why a rebuilt database never used to reach an installed app at all. The manifest makes the
// question cheap (a few hundred bytes against 170MB), so it is asked once per launch, after the
// reader already has a working database, and it only ever REPORTS: replacing the file is a large
// download and stays the reader's decision, taken through the same consent path as the first one.
window.dgCheckOfflineUpdate = async function () {
    try {
        await ready;
        const status = await call('check', { distBase: DIST_BASE });
        if (!status || status.unknown || status.current) return status;
        if (!status.schema_supported) {
            // A newer database than this build of the app understands. Downloading it would only
            // replace a working reader with a broken one.
            window.dispatchEvent(new CustomEvent('dg:update-blocked', { detail: status }));
            return status;
        }
        window.dispatchEvent(new CustomEvent('dg:update-available', { detail: status }));
        return status;
    } catch (e) { return null; }
};

// Runs on the reader's say-so, never on the check above.
window.dgUpdateOfflineData = async function (info) {
    if (!(await hasNetworkConsent(info))) throw new Error('offline-data-download-declined');
    return openWithDownload('update');
};

// Settings is a separate page and a separate JS realm — it cannot reach the worker, and probing
// OPFS from there would mean installing the SAH pool a second time while this page holds it. So
// the state it needs is left in localStorage, which both pages share, and written only from here,
// where it is actually known.
const STATE_KEY = 'dg.offline.state';
const WANT_UPDATE_KEY = 'dg.offline.wantUpdate';

function rememberState(patch) {
    try {
        const previous = JSON.parse(localStorage.getItem(STATE_KEY) || '{}');
        localStorage.setItem(STATE_KEY, JSON.stringify({ ...previous, ...patch, at: Date.now() }));
    } catch (e) { /* private mode, quota — the row degrades to "unknown", nothing breaks */ }
}

ready.then(async (opened) => {
    rememberState({ present: true, build_id: opened && opened.build_id, update: null });

    // Settings' button cannot start a 170MB download itself (wrong realm), so it records the
    // intent and sends the reader here, the same navigation the row already used.
    let wanted = false;
    try { wanted = localStorage.getItem(WANT_UPDATE_KEY) === '1'; localStorage.removeItem(WANT_UPDATE_KEY); }
    catch (e) { /* ignore */ }
    if (wanted) {
        try {
            const result = await window.dgUpdateOfflineData();
            rememberState({ build_id: result.build_id, update: null });
            return;
        } catch (e) { /* fall through to the ordinary check below */ }
    }

    const status = await window.dgCheckOfflineUpdate();
    if (status && !status.unknown && !status.current) {
        rememberState({ update: { build_id: status.build_id, bytes: status.bytes, built_at: status.built_at } });
    }
}, () => {});
