// Offline data shim for the app. This file owns no UI: www/index.html is dg-node's own
// search/index.html, generated by build-page.js, and its inline SPA engine plus the real
// search-render.js / megareader.js / common.js drive everything the reader sees.
//
// Its only job is to intercept the handful of fetch() calls that need data and answer them
// locally. What answers them is NOT a reimplementation of the site's API: it is dg-node's own
// core/search-core.js, bundled by build-core-bundle.js and running in db-worker.js over a slice
// of the same dg.db the server queries. The app used to carry its own SQL, its own translator
// selection and its own result assembly, and they drifted — different counts, no match inside a
// compound, one translator per language, no punctuation stripping. Now there is one
// implementation, and test/core-parity.mjs diffs its answers against the site's.
//
// The database lives in the worker because OPFS hands out synchronous access handles only there,
// and synchronous access is what keeps a large database on disk instead of in memory.
//
// TOC (/api/toc, /api/toc/book/:code) stays a build-time snapshot of the live server's JSON (see
// build-toc-snapshot.js): its branch-title resolution changes with the corpus, not per request.

// App Shortcuts (long-press launcher icon, Android/MainActivity.java + res/xml/shortcuts.xml)
// can't loadUrl() straight to a deep path — the static asset server behind this origin has no
// file at e.g. "/toc/pli-tv-bu-pm" (only index.html at root), same reason a raw reload of a
// pushState'd URL 404s. MainActivity instead loads "/?_nativeRoute=<path>" on the root, and this
// runs FIRST — before the page's own bootstrap script (search/index.html's inline $(document).
// ready handler) ever reads window.location — rewriting the visible URL to the real target via
// the same history.replaceState() trick the SPA already uses for its own pushState navigation.
// A plain browser load (no native shortcut involved) never has this param, so this is a no-op.
(function rewriteNativeShortcutRoute() {
    const params = new URLSearchParams(location.search);
    const route = params.get('_nativeRoute');
    if (route) history.replaceState(null, '', route);

    // "favorites" App Shortcut (res/xml/shortcuts.xml) — no dedicated route exists for
    // Favorites/History (they live inside the Quick Modal, not the SPA router), so this just
    // opens the modal once its lazy-load stub (settings-bundle.js) exists. No tab argument needed:
    // tab-fav (Favorites+History combined) is already the modal's default active tab.
    if (params.has('_openQuickModal')) {
        history.replaceState(null, '', route || location.pathname);
        window.addEventListener('load', () => {
            if (typeof window.toggleQuickModal === 'function') window.toggleQuickModal();
        });
    }

})();

// Where the offline database is published: siteroot/mobile-data in dg-node, served from the live
// host. One file: dg-mobile.db, a language slice of the server's own dg.db, cut by
// build-app-db.js — named apart from it so the two never get confused on the same machine.
//
// Overridable so the app can be pointed at a local copy: the end-to-end test serves the database
// from the same origin as the page, and a staging build may want a different host. Set
// window.DG_DIST_BASE before this script runs — it is the first script on the page, so that means
// an init script or an injected tag above it.
const DIST_BASE = (typeof window !== 'undefined' && window.DG_DIST_BASE) || 'https://dhamma.gift/mobile-data';

let worker = null;
let ready = null;
let nextCallId = 1;
const pending = new Map();

function startWorker() {
    // A module worker: @sqlite.org/sqlite-wasm ships ESM only, and the core bundle is emitted as a
    // module for the same reason.
    const w = new Worker('/db-worker.js', { type: 'module' });
    w.onmessage = (event) => {
        const msg = event.data || {};
        // Unsolicited progress, so the UI can show something during the first download.
        if (msg.type === 'progress') {
            window.dispatchEvent(new CustomEvent('dg:dl-progress', {
                detail: { name: 'dg-mobile.db', step: 1, totalSteps: 1, loaded: msg.loaded, total: msg.total },
            }));
            return;
        }
        if (msg.type === 'downloading') return;
        const entry = pending.get(msg.id);
        if (!entry) return;
        pending.delete(msg.id);
        msg.ok ? entry.resolve(msg.result) : entry.reject(new Error(msg.error));
    };
    w.onerror = (e) => {
        // A worker that fails to start (a bad import, a missing wasm) otherwise leaves every
        // caller hanging forever, which on a device looks like a frozen app rather than an error.
        const err = new Error('data worker failed: ' + (e.message || 'unknown'));
        for (const { reject } of pending.values()) reject(err);
        pending.clear();
    };
    return w;
}

function call(op, args) {
    return new Promise((resolve, reject) => {
        const id = nextCallId++;
        pending.set(id, { resolve, reject });
        worker.postMessage({ id, op, args });
    });
}

// Owner: "предупредить что даты много, и если мобильные данные — получить согласие" — Wi-Fi
// proceeds immediately (just the progress banner); anything else (cellular/unknown/no plugin
// info) asks first through a UI-owned dialog, wired by a plain event so this file needs no DOM
// code (offline-status.js listens for 'dg:need-consent' and calls the carried resolve).
async function hasNetworkConsent() {
    const Network = window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins.Network;
    if (!Network) return true;
    let status;
    try { status = await Network.getStatus(); } catch (e) { return true; }
    if (status.connectionType === 'wifi') return true;
    return new Promise(resolve => {
        window.dispatchEvent(new CustomEvent('dg:need-consent', { detail: { resolve } }));
    });
}

async function loadData() {
    worker = worker || startWorker();

    // Consent is asked only when there is something to download. A returning reader whose copy is
    // already in OPFS must stay fully offline-capable and never wait on a network status call
    // that could itself hang — so the worker is asked whether the file is there first, and only a
    // missing one leads to a question. The dialog lives on this side because a worker has no DOM.
    const status = await call('status', {});
    if (!status.present && !(await hasNetworkConsent())) {
        throw new Error('offline-data-download-declined');
    }
    return call('open', { distBase: DIST_BASE });
}

function jsonResponse(obj, status = 200) {
    return new Response(JSON.stringify(obj), { status, headers: { 'Content-Type': 'application/json' } });
}

// A worker result may carry the status the route would have set: an unknown sutta is a 404, and
// answering 200 with an error body would be a different contract from the site's.
function respond(result) {
    if (result && result.__status) {
        const { __status, ...body } = result;
        return jsonResponse(body, __status);
    }
    return jsonResponse(result);
}

function withLoadingEvent(fn) {
    window.dispatchEvent(new CustomEvent('dg:api-loading', { detail: { active: true } }));
    return fn().finally(() => {
        window.dispatchEvent(new CustomEvent('dg:api-loading', { detail: { active: false } }));
    });
}

// Installed synchronously, at the very top of <head> (see build-page.js) — before any other
// script or asset on the page can issue a real fetch(). Requests this doesn't recognise pass
// straight through to the real fetch: static JSON/HTML/CSS/JS all resolve as plain local files.
function installFetchShim() {
    const realFetch = window.fetch.bind(window);
    window.fetch = async (input, init) => {
        const url = typeof input === 'string' ? input : input.url;
        let parsed;
        try { parsed = new URL(url, location.href); } catch (e) { return realFetch(input, init); }
        const p = parsed.pathname;
        const qs = parsed.searchParams;

        if (p.startsWith('/api/text/')) {
            return withLoadingEvent(async () => {
                await ready;
                return respond(await call('text', {
                    suttaId: decodeURIComponent(p.slice('/api/text/'.length)).toLowerCase(),
                    mode: qs.get('mode'),
                    langs: qs.get('langs'),
                    lang: qs.get('lang'),
                    translators: qs.get('translators'),
                    multiFor: qs.get('multiFor'),
                }));
            });
        }
        if (p.startsWith('/api/nav/')) {
            await ready;
            return respond(await call('nav', {
                suttaId: decodeURIComponent(p.slice('/api/nav/'.length)).toLowerCase(),
                scope: qs.get('scope'),
            }));
        }
        // TOC — baked at build time (build-toc-snapshot.js curls the live server once) rather than
        // reimplemented: dg-fastify.js's branch-title resolution (colophon lookups, curated SN
        // overrides) only changes when the corpus or toc-books.json does, which is the same
        // cadence as the database itself. No `await ready` — these are static files.
        if (p === '/api/toc') return realFetch('/api-snapshots/toc.json', init);
        if (p.startsWith('/api/toc/book/')) {
            return realFetch(`/api-snapshots/toc-book-${decodeURIComponent(p.slice('/api/toc/book/'.length))}.json`, init);
        }
        // The file is already bundled at reader/{bu,bi}-pm-fragment.html — only the URL differs.
        if (p.startsWith('/api/patimokkha-fragment/')) {
            const side = p.slice('/api/patimokkha-fragment/'.length);
            if (side !== 'bu' && side !== 'bi') return jsonResponse({ error: 'Not found' }, 404);
            return realFetch(`/reader/${side}-pm-fragment.html`, init);
        }
        if (p === '/search/enrich') {
            await ready;
            return respond(await call('enrich', {
                q: qs.get('q') || '', ids: qs.get('ids') || '', langs: qs.get('langs') || 'ru,en',
                scope: qs.get('scope') || 'default', exact: qs.get('exact') === 'true',
                lb: parseInt(qs.get('lb')) || 0, la: parseInt(qs.get('la')) || 0,
            }));
        }
        if (p === '/search' || (p.startsWith('/search/') && p !== '/search/enrich')) {
            return withLoadingEvent(async () => {
                await ready;
                return respond(await call('search', {
                    q: p === '/search' ? (qs.get('q') || '') : decodeURIComponent(p.slice('/search/'.length)),
                    scope: qs.get('scope') || 'default',
                    langs: qs.get('langs') || 'ru,en',
                    exact: qs.get('exact') === 'true',
                    lb: parseInt(qs.get('lb')) || 0,
                    la: parseInt(qs.get('la')) || 0,
                    fast: qs.get('fast') === '1',
                }));
            });
        }
        return realFetch(input, init);
    };
}

installFetchShim();
ready = loadData();
window.dgOfflineReady = ready;
ready.catch(() => {}); // declining rejects `ready`; real awaiters see it through their own await

// Settings' "Download now"/"Re-download" button and offline-status.js's retry share this path.
window.dgRetryOfflineDownload = function () {
    ready = loadData();
    window.dgOfflineReady = ready;
    ready.catch(() => {});
    return ready;
};
