// Offline data shim for the app. This file owns no UI: www/index.html is dg-node's own
// search/index.html, generated by build-page.js, and its inline SPA engine plus the real
// search-render.js / megareader.js / common.js drive everything the reader sees.
//
// Its only job is to intercept the handful of fetch() calls that need data and answer them
// locally. What answers them is NOT a reimplementation of the site's API: it is dg-node's own
// core/search-core.js, bundled by build-core-bundle.js and running in db-worker.js over a slice
// of the same dg.db the server queries. The app used to carry its own SQL, its own translator
// selection and its own result assembly, and they drifted — different counts, no match inside a
// compound, one translator per language, no punctuation stripping. Now there is one
// implementation, and test/core-parity.mjs diffs its answers against the site's.
//
// The database lives in the worker because OPFS hands out synchronous access handles only there,
// and synchronous access is what keeps a large database on disk instead of in memory.
//
// TOC (/api/toc, /api/toc/book/:code) stays a build-time snapshot of the live server's JSON (see
// build-toc-snapshot.js): its branch-title resolution changes with the corpus, not per request.

// App Shortcuts (long-press launcher icon, Android/MainActivity.java + res/xml/shortcuts.xml)
// can't loadUrl() straight to a deep path — the static asset server behind this origin has no
// file at e.g. "/toc/pli-tv-bu-pm" (only index.html at root), same reason a raw reload of a
// pushState'd URL 404s. MainActivity instead loads "/?_nativeRoute=<path>" on the root, and this
// runs FIRST — before the page's own bootstrap script (search/index.html's inline $(document).
// ready handler) ever reads window.location — rewriting the visible URL to the real target via
// the same history.replaceState() trick the SPA already uses for its own pushState navigation.
// A plain browser load (no native shortcut involved) never has this param, so this is a no-op.
(function rewriteNativeShortcutRoute() {
    const params = new URLSearchParams(location.search);
    const route = params.get('_nativeRoute');
    if (route) history.replaceState(null, '', route);

    // "favorites" App Shortcut (res/xml/shortcuts.xml) — no dedicated route exists for
    // Favorites/History (they live inside the Quick Modal, not the SPA router), so this just
    // opens the modal once its lazy-load stub (settings-bundle.js) exists. No tab argument needed:
    // tab-fav (Favorites+History combined) is already the modal's default active tab.
    if (params.has('_openQuickModal')) {
        history.replaceState(null, '', route || location.pathname);
        window.addEventListener('load', () => {
            if (typeof window.toggleQuickModal === 'function') window.toggleQuickModal();
        });
    }

})();

// Where the offline database is published: siteroot/mobile-data in dg-node, served from the live
// host. One file: dg-mobile.db, a language slice of the server's own dg.db, cut by
// build-app-db.js — named apart from it so the two never get confused on the same machine.
//
// Overridable so the app can be pointed at a local copy: the end-to-end test serves the database
// from the same origin as the page, and a staging build may want a different host. Set
// window.DG_DIST_BASE before this script runs — it is the first script on the page, so that means
// an init script or an injected tag above it.
const DIST_BASE = (typeof window !== 'undefined' && window.DG_DIST_BASE) || 'https://dhamma.gift/mobile-data';

let worker = null;
let ready = null;
let nextCallId = 1;
const pending = new Map();

function startWorker() {
    // A module worker: @sqlite.org/sqlite-wasm ships ESM only, and the core bundle is emitted as a
    // module for the same reason.
    const w = new Worker('/db-worker.js', { type: 'module' });
    w.onmessage = (event) => {
        const msg = event.data || {};
        // Unsolicited progress, so the UI can show something during the first download.
        if (msg.type === 'progress') {
            window.dispatchEvent(new CustomEvent('dg:dl-progress', {
                detail: {
                    name: 'dg-mobile.db', step: 1, totalSteps: 1,
                    loaded: msg.loaded, total: msg.total, phase: msg.phase || 'download',
                },
            }));
            return;
        }
        if (msg.type === 'downloading') return;
        const entry = pending.get(msg.id);
        if (!entry) return;
        pending.delete(msg.id);
        msg.ok ? entry.resolve(msg.result) : entry.reject(new Error(msg.error));
    };
    w.onerror = (e) => {
        // A worker that fails to start (a bad import, a missing wasm) otherwise leaves every
        // caller hanging forever, which on a device looks like a frozen app rather than an error.
        const err = new Error('data worker failed: ' + (e.message || 'unknown'));
        for (const { reject } of pending.values()) reject(err);
        pending.clear();
    };
    return w;
}

function call(op, args) {
    return new Promise((resolve, reject) => {
        const id = nextCallId++;
        pending.set(id, { resolve, reject });
        worker.postMessage({ id, op, args });
    });
}

// Owner: "предупредить что даты много, и если мобильные данные — получить согласие" — Wi-Fi
// proceeds immediately (just the progress banner); anything else (cellular/unknown/no plugin
// info) asks first through a UI-owned dialog, wired by a plain event so this file needs no DOM
// code (offline-status.js listens for 'dg:need-consent' and calls the carried resolve).
async function hasNetworkConsent(info) {
    const Network = window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins.Network;
    if (!Network) return true;
    let status;
    try { status = await Network.getStatus(); } catch (e) { return true; }
    if (status.connectionType === 'wifi') return true;
    return new Promise(resolve => {
        // bytes comes from the published manifest, so the question names the size of the file that
        // is actually about to be transferred rather than a figure baked into the app.
        window.dispatchEvent(new CustomEvent('dg:need-consent', {
            detail: {
                resolve,
                bytes: info && info.bytes,
                stored_bytes: info && info.stored_bytes,
                langs: info && info.langs,
            },
        }));
    });
}

// Android's DownloadManager, through DgDownloader.java, when it is there. The reason it is worth
// the detour: a WebView that goes to the background gets throttled and then reclaimed, and 170MB
// of progress goes with it — owner asked to be able to minimise the app and to see progress in
// the shade, and neither is possible from inside the WebView. Notification permission grants the
// right to show something, not the right to keep running; only the system's own downloader (or a
// foreground service of our own, which is far more machinery) actually continues.
//
// It also resumes after a dropped connection instead of restarting 170MB, and survives a reboot.
//
// Absent — a browser, the dev server — everything below is skipped and the worker streams the
// file straight from the network into OPFS as before. That path costs less disk (no second copy)
// and is the right one when there is no app to background.
function nativeDownloader() {
    const plugins = window.Capacitor && window.Capacitor.Plugins;
    return (plugins && plugins.DgDownloader) || null;
}

const DOWNLOAD_ID_KEY = 'dg.offline.downloadId';

// Polls until the system is done, feeding the same progress event the in-app card already draws,
// so the reader sees one bar whether or not the download is native. The id is remembered, so a
// launch that lands while a download is still running rejoins it instead of starting a second.
async function runNativeDownload(downloader, url, ru) {
    let id = null;
    try { id = Number(localStorage.getItem(DOWNLOAD_ID_KEY)) || null; } catch (e) { /* ignore */ }

    if (id) {
        const existing = await downloader.status({ id }).catch(() => null);
        if (!existing || existing.state === 'missing' || existing.state === 'failed') id = null;
    }
    if (!id) {
        const started = await downloader.start({
            url,
            title: 'Dhamma.gift',
            description: ru ? 'Тексты и переводы для работы без сети' : 'Texts and translations for offline use',
        });
        id = started && started.id;
        if (id === undefined || id === null) throw new Error('the system downloader returned no id');
        try { localStorage.setItem(DOWNLOAD_ID_KEY, String(id)); } catch (e) { /* ignore */ }
    }

    for (;;) {
        const status = await downloader.status({ id });
        if (status.state === 'done') {
            try { localStorage.removeItem(DOWNLOAD_ID_KEY); } catch (e) { /* ignore */ }
            return { id, path: status.path };
        }
        if (status.state === 'failed' || status.state === 'missing') {
            try { localStorage.removeItem(DOWNLOAD_ID_KEY); } catch (e) { /* ignore */ }
            await downloader.clear({ id }).catch(() => {});
            throw new Error(status.reason || 'the system download did not complete');
        }
        window.dispatchEvent(new CustomEvent('dg:dl-progress', {
            detail: {
                loaded: status.loaded || 0, total: status.total || 0,
                phase: 'download', native: true, waiting: status.state !== 'running',
            },
        }));
        await new Promise(resolve => setTimeout(resolve, 700));
    }
}

async function loadData() {
    worker = worker || startWorker();

    // Consent is asked only when there is something to download. A returning reader whose copy is
    // already in OPFS must stay fully offline-capable and never wait on a network status call
    // that could itself hang — so the worker is asked whether the file is there first, and only a
    // missing one leads to a question. The dialog lives on this side because a worker has no DOM.
    const status = await call('status', { distBase: DIST_BASE });
    if (status.present) return call('open', { distBase: DIST_BASE });
    if (!(await hasNetworkConsent(status))) throw new Error('offline-data-download-declined');
    return openWithDownload();
}

// One path for "there is no database yet, get one": the system downloads it when it can, and the
// worker imports whatever landed. The temporary file is deleted the moment the import succeeds —
// otherwise the library is carried twice for the life of the install.
async function openWithDownload(op = 'open') {
    const downloader = nativeDownloader();
    if (!downloader) return call(op, { distBase: DIST_BASE });

    const ru = (localStorage.getItem('dhammaLanguage') || localStorage.getItem('siteLanguage') || 'en') === 'ru';
    // The worker reads the manifest and says which file to fetch — the published name, and the
    // compressed one when there is one. This used to be a hardcoded dg-mobile.db, which is not
    // what a server that publishes under another name (or only a .gz) has to offer.
    const plan = await call('plan', { distBase: DIST_BASE });
    const { id, path } = await runNativeDownload(downloader, plan.url, ru);
    const sourceUrl = window.Capacitor.convertFileSrc(path);
    try {
        return await call(op, { distBase: DIST_BASE, sourceUrl });
    } finally {
        await downloader.clear({ id }).catch(() => {});
    }
}

function jsonResponse(obj, status = 200) {
    return new Response(JSON.stringify(obj), { status, headers: { 'Content-Type': 'application/json' } });
}

// A worker result may carry the status the route would have set: an unknown sutta is a 404, and
// answering 200 with an error body would be a different contract from the site's.
function respond(result) {
    if (result && result.__status) {
        const { __status, ...body } = result;
        return jsonResponse(body, __status);
    }
    return jsonResponse(result);
}

function withLoadingEvent(fn) {
    window.dispatchEvent(new CustomEvent('dg:api-loading', { detail: { active: true } }));
    return fn().finally(() => {
        window.dispatchEvent(new CustomEvent('dg:api-loading', { detail: { active: false } }));
    });
}

// Installed synchronously, at the very top of <head> (see build-page.js) — before any other
// script or asset on the page can issue a real fetch(). Requests this doesn't recognise pass
// straight through to the real fetch: static JSON/HTML/CSS/JS all resolve as plain local files.
function installFetchShim() {
    const realFetch = window.fetch.bind(window);
    window.fetch = async (input, init) => {
        const url = typeof input === 'string' ? input : input.url;
        let parsed;
        try { parsed = new URL(url, location.href); } catch (e) { return realFetch(input, init); }
        const p = parsed.pathname;
        const qs = parsed.searchParams;

        if (p.startsWith('/api/text/')) {
            return withLoadingEvent(async () => {
                await ready;
                return respond(await call('text', {
                    suttaId: decodeURIComponent(p.slice('/api/text/'.length)).toLowerCase(),
                    mode: qs.get('mode'),
                    langs: qs.get('langs'),
                    lang: qs.get('lang'),
                    translators: qs.get('translators'),
                    multiFor: qs.get('multiFor'),
                }));
            });
        }
        if (p.startsWith('/api/nav/')) {
            await ready;
            return respond(await call('nav', {
                suttaId: decodeURIComponent(p.slice('/api/nav/'.length)).toLowerCase(),
                scope: qs.get('scope'),
            }));
        }
        // TOC — baked at build time (build-toc-snapshot.js curls the live server once) rather than
        // reimplemented: dg-fastify.js's branch-title resolution (colophon lookups, curated SN
        // overrides) only changes when the corpus or toc-books.json does, which is the same
        // cadence as the database itself. No `await ready` — these are static files.
        if (p === '/api/toc') return realFetch('/api-snapshots/toc.json', init);
        if (p.startsWith('/api/toc/book/')) {
            return realFetch(`/api-snapshots/toc-book-${decodeURIComponent(p.slice('/api/toc/book/'.length))}.json`, init);
        }
        // The file is already bundled at reader/{bu,bi}-pm-fragment.html — only the URL differs.
        if (p.startsWith('/api/patimokkha-fragment/')) {
            const side = p.slice('/api/patimokkha-fragment/'.length);
            if (side !== 'bu' && side !== 'bi') return jsonResponse({ error: 'Not found' }, 404);
            return realFetch(`/reader/${side}-pm-fragment.html`, init);
        }
        if (p === '/search/enrich') {
            await ready;
            return respond(await call('enrich', {
                q: qs.get('q') || '', ids: qs.get('ids') || '', langs: qs.get('langs') || 'ru,en',
                scope: qs.get('scope') || 'default', exact: qs.get('exact') === 'true',
                lb: parseInt(qs.get('lb')) || 0, la: parseInt(qs.get('la')) || 0,
            }));
        }
        if (p === '/search' || (p.startsWith('/search/') && p !== '/search/enrich')) {
            return withLoadingEvent(async () => {
                await ready;
                return respond(await call('search', {
                    q: p === '/search' ? (qs.get('q') || '') : decodeURIComponent(p.slice('/search/'.length)),
                    scope: qs.get('scope') || 'default',
                    langs: qs.get('langs') || 'ru,en',
                    exact: qs.get('exact') === 'true',
                    lb: parseInt(qs.get('lb')) || 0,
                    la: parseInt(qs.get('la')) || 0,
                    fast: qs.get('fast') === '1',
                }));
            });
        }
        return realFetch(input, init);
    };
}

installFetchShim();
ready = loadData();
window.dgOfflineReady = ready;
ready.catch(() => {}); // declining rejects `ready`; real awaiters see it through their own await

// Settings' "Download now"/"Re-download" button and offline-status.js's retry share this path.
window.dgRetryOfflineDownload = function () {
    ready = loadData();
    window.dgOfflineReady = ready;
    ready.catch(() => {});
    return ready;
};

// A copy in OPFS is used forever unless something asks whether it is still the current one — which
// is why a rebuilt database never used to reach an installed app at all. The manifest makes the
// question cheap (a few hundred bytes against 170MB), so it is asked once per launch, after the
// reader already has a working database, and it only ever REPORTS: replacing the file is a large
// download and stays the reader's decision, taken through the same consent path as the first one.
window.dgCheckOfflineUpdate = async function () {
    try {
        await ready;
        const status = await call('check', { distBase: DIST_BASE });
        if (!status || status.unknown || status.current) return status;
        if (!status.schema_supported) {
            // A newer database than this build of the app understands. Downloading it would only
            // replace a working reader with a broken one.
            window.dispatchEvent(new CustomEvent('dg:update-blocked', { detail: status }));
            return status;
        }
        window.dispatchEvent(new CustomEvent('dg:update-available', { detail: status }));
        return status;
    } catch (e) { return null; }
};

// Runs on the reader's say-so, never on the check above.
window.dgUpdateOfflineData = async function (info) {
    if (!(await hasNetworkConsent(info))) throw new Error('offline-data-download-declined');
    return openWithDownload('update');
};

// Settings is a separate page and a separate JS realm — it cannot reach the worker, and probing
// OPFS from there would mean installing the SAH pool a second time while this page holds it. So
// the state it needs is left in localStorage, which both pages share, and written only from here,
// where it is actually known.
const STATE_KEY = 'dg.offline.state';
const WANT_UPDATE_KEY = 'dg.offline.wantUpdate';

function rememberState(patch) {
    try {
        const previous = JSON.parse(localStorage.getItem(STATE_KEY) || '{}');
        localStorage.setItem(STATE_KEY, JSON.stringify({ ...previous, ...patch, at: Date.now() }));
    } catch (e) { /* private mode, quota — the row degrades to "unknown", nothing breaks */ }
}

ready.then(async (opened) => {
    rememberState({ present: true, build_id: opened && opened.build_id, update: null });

    // Settings' button cannot start a 170MB download itself (wrong realm), so it records the
    // intent and sends the reader here, the same navigation the row already used.
    let wanted = false;
    try { wanted = localStorage.getItem(WANT_UPDATE_KEY) === '1'; localStorage.removeItem(WANT_UPDATE_KEY); }
    catch (e) { /* ignore */ }
    if (wanted) {
        try {
            const result = await window.dgUpdateOfflineData();
            rememberState({ build_id: result.build_id, update: null });
            return;
        } catch (e) { /* fall through to the ordinary check below */ }
    }

    const status = await window.dgCheckOfflineUpdate();
    if (status && !status.unknown && !status.current) {
        rememberState({ update: {
            build_id: status.build_id, bytes: status.bytes, stored_bytes: status.stored_bytes,
            built_at: status.built_at,
        } });
    }
}, () => {});
